package DefenceSystem;

/**
 *
 * @author Shameel Shajaad
 */
public class Helicopter extends javax.swing.JFrame implements DefenceSystemObserver {

    private int position;

    /**
     * Creates new form Helicopter
     */
    public Helicopter() {
        initComponents();
        setTitle("Helicopter");
        this.setLocationRelativeTo(null);
        setVisible(true);

        jSpinnerSoldierCount.setValue(100);
        jSpinnerAmmoCount.setValue(500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAreaCleared = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jScrollPaneTextArea = new javax.swing.JScrollPane();
        jTextAreaMessageArea = new javax.swing.JTextArea();
        jTextFieldTextMessage = new javax.swing.JTextField();
        jButtonSendButton = new javax.swing.JButton();
        jButtonSendASoldier = new javax.swing.JButton();
        jButtonShoot = new javax.swing.JButton();
        jButtonLaserOperation = new javax.swing.JButton();
        jSpinnerSoldierCount = new javax.swing.JSpinner();
        jSpinnerAmmoCount = new javax.swing.JSpinner();
        jLabelSoldierCount = new javax.swing.JLabel();
        jLabelAmmoCount = new javax.swing.JLabel();
        jCheckBoxPosition = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAreaCleared.setText("Area Not Cleared");

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(100);

        jTextAreaMessageArea.setEditable(false);
        jTextAreaMessageArea.setColumns(20);
        jTextAreaMessageArea.setLineWrap(true);
        jTextAreaMessageArea.setRows(5);
        jScrollPaneTextArea.setViewportView(jTextAreaMessageArea);

        jButtonSendButton.setText("SEND");
        jButtonSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendButtonActionPerformed(evt);
            }
        });

        jButtonSendASoldier.setText("Send a Soldier");
        jButtonSendASoldier.setEnabled(false);

        jButtonShoot.setText("Shoot");
        jButtonShoot.setEnabled(false);

        jButtonLaserOperation.setText("Laser Operation");
        jButtonLaserOperation.setEnabled(false);

        jLabelSoldierCount.setText("Soldier Count");

        jLabelAmmoCount.setText("Ammo Count");

        jCheckBoxPosition.setText("Position");
        jCheckBoxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPositionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLaserOperation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSendASoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPaneTextArea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldTextMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSendButton)))
                        .addGap(12, 12, 12)))
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAreaCleared)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinnerSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSoldierCount)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSendASoldier)
                            .addComponent(jButtonShoot)
                            .addComponent(jSpinnerAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAmmoCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLaserOperation)
                            .addComponent(jCheckBoxPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneTextArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTextMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSendButton))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPositionActionPerformed

    private void jButtonSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendButtonActionPerformed
        String message = "Helicopter: " + jTextFieldTextMessage.getText();
        jTextAreaMessageArea.append(message + "\n");
        MainController.setDefenceMessage(message);
    }//GEN-LAST:event_jButtonSendButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLaserOperation;
    private javax.swing.JButton jButtonSendASoldier;
    private javax.swing.JButton jButtonSendButton;
    private javax.swing.JButton jButtonShoot;
    private javax.swing.JCheckBox jCheckBoxPosition;
    private javax.swing.JLabel jLabelAmmoCount;
    private javax.swing.JLabel jLabelAreaCleared;
    private javax.swing.JLabel jLabelSoldierCount;
    private javax.swing.JScrollPane jScrollPaneTextArea;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinnerAmmoCount;
    private javax.swing.JSpinner jSpinnerSoldierCount;
    private javax.swing.JTextArea jTextAreaMessageArea;
    private javax.swing.JTextField jTextFieldTextMessage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getMsgMain(String Msg) {
        try {
            javax.swing.text.Document doc = jTextAreaMessageArea.getDocument();
            doc.insertString(doc.getLength(), "Main Controller: " + Msg + "\n", null);
            jTextAreaMessageArea.setCaretPosition(doc.getLength());
        } catch (javax.swing.text.BadLocationException e) {

        }
    }

    @Override
    public void update(int position) {
        this.position = position;
        updateButtons();
    }

    @Override
    public void areaClearLabel(boolean clear) {
        if (clear) {
            jLabelAreaCleared.setText("Area Cleared");
        } else {
            jLabelAreaCleared.setText("Area Not Cleared");
        }
    }

    @Override
    public void updateButtons() {
        if (jCheckBoxPosition.isSelected()) {
            jButtonShoot.setEnabled(position >= 20);
            jButtonSendASoldier.setEnabled(position >= 40);
            jButtonLaserOperation.setEnabled(position >= 60);
        } else {
            jButtonShoot.setEnabled(false);
            jButtonSendASoldier.setEnabled(false);
            jButtonLaserOperation.setEnabled(false);
        }
    }

    @Override
    public String getSoldierCount(int index) {
        if (index == 1) {
            return String.valueOf(jSpinnerSoldierCount.getValue());
        }
        return null;

    }
}
