/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DefenceSystem;

/**
 *
 * @author Shameel Shajaad
 */
public class MainController extends javax.swing.JFrame {

    private final DefenceSystemObservableInterface defenceSystemObservableInterface;

    /**
     * Creates new form MainController
     */
    public MainController(DefenceSystemObservableInterface defenceSystemObservableInterface) {
        initComponents();
        this.defenceSystemObservableInterface = defenceSystemObservableInterface;
        setTitle("Main Controller");
        this.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxSelectDefence = new javax.swing.JComboBox<>();
        jButtonCollectInformations = new javax.swing.JButton();
        jCheckBoxAreaClear = new javax.swing.JCheckBox();
        jScrollPaneTextArea = new javax.swing.JScrollPane();
        jTextAreaTextAreaMain = new javax.swing.JTextArea();
        jLabelSoldierCount = new javax.swing.JLabel();
        jLabelFuelAmount = new javax.swing.JLabel();
        jLabelAmmoCount = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jSliderPosition = new javax.swing.JSlider();
        jTextFieldTextMessage = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jLabelValueSoldierCount = new javax.swing.JLabel();
        jLabelValueAmmoCount = new javax.swing.JLabel();
        jLabelValueFuelAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxSelectDefence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Helicopter", "Tank", "Submarine" }));
        jComboBoxSelectDefence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectDefenceActionPerformed(evt);
            }
        });

        jButtonCollectInformations.setText("Collect Informations");

        jCheckBoxAreaClear.setText("Area Clear");
        jCheckBoxAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAreaClearActionPerformed(evt);
            }
        });

        jTextAreaTextAreaMain.setEditable(false);
        jTextAreaTextAreaMain.setColumns(20);
        jTextAreaTextAreaMain.setLineWrap(true);
        jTextAreaTextAreaMain.setRows(5);
        jScrollPaneTextArea.setViewportView(jTextAreaTextAreaMain);

        jLabelSoldierCount.setText("Soldier Count");

        jLabelFuelAmount.setText("Fuel Amount");

        jLabelAmmoCount.setText("Ammo Count");

        jLabelPosition.setText("Position");

        jSliderPosition.setMajorTickSpacing(20);
        jSliderPosition.setMinorTickSpacing(10);
        jSliderPosition.setPaintLabels(true);
        jSliderPosition.setPaintTicks(true);
        jSliderPosition.setSnapToTicks(true);
        jSliderPosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPositionStateChanged(evt);
            }
        });

        jButtonSend.setText("SEND");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jLabelValueSoldierCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValueSoldierCount.setText(" ");

        jLabelValueAmmoCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValueAmmoCount.setText(" ");

        jLabelValueFuelAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValueFuelAmount.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxSelectDefence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCollectInformations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAreaClear)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelValueAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelValueFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelValueSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTextMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelectDefence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCollectInformations)
                    .addComponent(jCheckBoxAreaClear))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSoldierCount)
                            .addComponent(jLabelValueSoldierCount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFuelAmount)
                            .addComponent(jLabelValueFuelAmount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAmmoCount)
                            .addComponent(jLabelValueAmmoCount))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSliderPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTextMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSend))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        String message = jTextFieldTextMessage.getText();

        if (!message.isEmpty()) {
            defenceSystemObservableInterface.getMsgMain(message);
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jCheckBoxAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAreaClearActionPerformed
        defenceSystemObservableInterface.areaClearLabel(jCheckBoxAreaClear.isSelected());
    }//GEN-LAST:event_jCheckBoxAreaClearActionPerformed

    private void jSliderPositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPositionStateChanged
        int position = jSliderPosition.getValue();
        defenceSystemObservableInterface.setPosition(position);
    }//GEN-LAST:event_jSliderPositionStateChanged

    private void jComboBoxSelectDefenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectDefenceActionPerformed
        int index=jComboBoxSelectDefence.getSelectedIndex();
        
        if(index==0){
            jLabelValueSoldierCount.setText(" ");
            jLabelValueFuelAmount.setText(" ");
            jLabelValueAmmoCount.setText(" ");
        }
        if(index==1){
            jLabelValueSoldierCount.setText(defenceSystemObservableInterface.getSoldierCount(index));
            jLabelValueAmmoCount.setText(defenceSystemObservableInterface.getAmmoCount(index));
            jLabelFuelAmount.setText(defenceSystemObservableInterface.getFuelAmount(index));
        }
        if(index==2){
            jLabelValueSoldierCount.setText(defenceSystemObservableInterface.getSoldierCount(index));
            jLabelValueAmmoCount.setText(defenceSystemObservableInterface.getAmmoCount(index));
            jLabelFuelAmount.setText(defenceSystemObservableInterface.getFuelAmount(index));
        }
        if(index==3){
            jLabelValueSoldierCount.setText(defenceSystemObservableInterface.getSoldierCount(index));
            jLabelValueAmmoCount.setText(defenceSystemObservableInterface.getAmmoCount(index));
            jLabelFuelAmount.setText(defenceSystemObservableInterface.getFuelAmount(index));
        }
    }//GEN-LAST:event_jComboBoxSelectDefenceActionPerformed

    public void updateInbox() {
        jTextAreaTextAreaMain.setText(" ");
    }

    public static void setDefenceMessage(String msg) {
        try {
            javax.swing.text.Document doc = jTextAreaTextAreaMain.getDocument();
            doc.insertString(doc.getLength(), msg + "\n", null);
            jTextAreaTextAreaMain.setCaretPosition(doc.getLength());
        } catch (javax.swing.text.BadLocationException e) {

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCollectInformations;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JCheckBox jCheckBoxAreaClear;
    private javax.swing.JComboBox<String> jComboBoxSelectDefence;
    private javax.swing.JLabel jLabelAmmoCount;
    private javax.swing.JLabel jLabelFuelAmount;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelSoldierCount;
    private javax.swing.JLabel jLabelValueAmmoCount;
    private javax.swing.JLabel jLabelValueFuelAmount;
    private javax.swing.JLabel jLabelValueSoldierCount;
    private javax.swing.JScrollPane jScrollPaneTextArea;
    private javax.swing.JSlider jSliderPosition;
    public static javax.swing.JTextArea jTextAreaTextAreaMain;
    private javax.swing.JTextField jTextFieldTextMessage;
    // End of variables declaration//GEN-END:variables
}
