/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DefenceSystem;

/**
 *
 * @author Shameel Shajaad
 */
public class Submarine extends javax.swing.JFrame implements DefenceSystemObserver {

    private int position;

    /**
     * Creates new form Helicopter
     */
    public Submarine() {
        initComponents();
        setTitle("Submarine");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAreaCleared = new javax.swing.JLabel();
        jSliderOxygen = new javax.swing.JSlider();
        jScrollPaneTextArea = new javax.swing.JScrollPane();
        jTextAreaMessageArea = new javax.swing.JTextArea();
        jTextFieldTextMessage = new javax.swing.JTextField();
        jButtonSendButton = new javax.swing.JButton();
        jButtonSonarOperation = new javax.swing.JButton();
        jButtonShoot = new javax.swing.JButton();
        jButtonTomahawkMissile = new javax.swing.JButton();
        jSpinnerSoldierCount = new javax.swing.JSpinner();
        jSpinnerAmmoCount = new javax.swing.JSpinner();
        jLabelSoldierCount = new javax.swing.JLabel();
        jLabelAmmoCount = new javax.swing.JLabel();
        jCheckBoxPosition = new javax.swing.JCheckBox();
        jButtonTrident2Missile = new javax.swing.JButton();
        jSliderEnergy = new javax.swing.JSlider();
        jLabelOxygen = new javax.swing.JLabel();
        jLabelEnergy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAreaCleared.setText("Area Not Cleared");

        jSliderOxygen.setMajorTickSpacing(20);
        jSliderOxygen.setMinorTickSpacing(10);
        jSliderOxygen.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderOxygen.setPaintLabels(true);
        jSliderOxygen.setPaintTicks(true);
        jSliderOxygen.setSnapToTicks(true);
        jSliderOxygen.setValue(100);

        jTextAreaMessageArea.setEditable(false);
        jTextAreaMessageArea.setColumns(20);
        jTextAreaMessageArea.setLineWrap(true);
        jTextAreaMessageArea.setRows(5);
        jScrollPaneTextArea.setViewportView(jTextAreaMessageArea);

        jTextFieldTextMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTextMessageActionPerformed(evt);
            }
        });

        jButtonSendButton.setText("SEND");
        jButtonSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendButtonActionPerformed(evt);
            }
        });

        jButtonSonarOperation.setText("Sonar Operation");
        jButtonSonarOperation.setEnabled(false);

        jButtonShoot.setText("Shoot");
        jButtonShoot.setEnabled(false);

        jButtonTomahawkMissile.setText("Tomahawk Missile");
        jButtonTomahawkMissile.setEnabled(false);

        jLabelSoldierCount.setText("Soldier Count");

        jLabelAmmoCount.setText("Ammo Count");

        jCheckBoxPosition.setText("Position");
        jCheckBoxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPositionActionPerformed(evt);
            }
        });

        jButtonTrident2Missile.setText("Trident-2 Missile");
        jButtonTrident2Missile.setEnabled(false);
        jButtonTrident2Missile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrident2MissileActionPerformed(evt);
            }
        });

        jSliderEnergy.setMajorTickSpacing(20);
        jSliderEnergy.setMinorTickSpacing(10);
        jSliderEnergy.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderEnergy.setPaintLabels(true);
        jSliderEnergy.setPaintTicks(true);
        jSliderEnergy.setSnapToTicks(true);
        jSliderEnergy.setValue(100);

        jLabelOxygen.setText("Oxygen");

        jLabelEnergy.setText("Energy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jButtonTomahawkMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonTrident2Missile, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonSonarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldTextMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOxygen)
                    .addComponent(jSliderOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAreaCleared)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinnerSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSoldierCount)
                                .addComponent(jLabelEnergy)
                                .addComponent(jLabelOxygen)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAmmoCount)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonSonarOperation)
                                        .addComponent(jButtonShoot)
                                        .addComponent(jSpinnerAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonTomahawkMissile)
                                    .addComponent(jCheckBoxPosition)
                                    .addComponent(jButtonTrident2Missile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPaneTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTextMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSendButton)))
                            .addComponent(jSliderEnergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSliderOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPositionActionPerformed

    private void jButtonTrident2MissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrident2MissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrident2MissileActionPerformed

    private void jTextFieldTextMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTextMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTextMessageActionPerformed

    private void jButtonSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendButtonActionPerformed
        String message = "Submarine: " + jTextFieldTextMessage.getText();
        MainController.setDefenceMessage(message);
    }//GEN-LAST:event_jButtonSendButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSendButton;
    private javax.swing.JButton jButtonShoot;
    private javax.swing.JButton jButtonSonarOperation;
    private javax.swing.JButton jButtonTomahawkMissile;
    private javax.swing.JButton jButtonTrident2Missile;
    private javax.swing.JCheckBox jCheckBoxPosition;
    private javax.swing.JLabel jLabelAmmoCount;
    private javax.swing.JLabel jLabelAreaCleared;
    private javax.swing.JLabel jLabelEnergy;
    private javax.swing.JLabel jLabelOxygen;
    private javax.swing.JLabel jLabelSoldierCount;
    private javax.swing.JScrollPane jScrollPaneTextArea;
    private javax.swing.JSlider jSliderEnergy;
    private javax.swing.JSlider jSliderOxygen;
    private javax.swing.JSpinner jSpinnerAmmoCount;
    private javax.swing.JSpinner jSpinnerSoldierCount;
    private javax.swing.JTextArea jTextAreaMessageArea;
    private javax.swing.JTextField jTextFieldTextMessage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getMsgMain(String Msg) {
        try {
            javax.swing.text.Document doc = jTextAreaMessageArea.getDocument();
            doc.insertString(doc.getLength(), "Main Controller: " + Msg + "\n", null);
            jTextAreaMessageArea.setCaretPosition(doc.getLength());
        } catch (javax.swing.text.BadLocationException e) {

        }
    }

    @Override
    public void update(int position) {
        this.position = position;
        updateButtons();
    }

    @Override
    public void areaClearLabel(boolean clear) {
        if (clear) {
            jLabelAreaCleared.setText("Area Cleared");
        } else {
            jLabelAreaCleared.setText("Area Not Cleared");
        }
    }

    @Override
    public void updateButtons() {
        if (jCheckBoxPosition.isSelected()) {
            jButtonShoot.setEnabled(position >= 20);
            jButtonSonarOperation.setEnabled(position >= 40);
            jButtonTomahawkMissile.setEnabled(position >= 60);
            jButtonTrident2Missile.setEnabled(position >= 80);
        } else {
            jButtonShoot.setEnabled(false);
            jButtonSonarOperation.setEnabled(false);
            jButtonTomahawkMissile.setEnabled(false);
            jButtonTrident2Missile.setEnabled(false);
        }
    }
}
